<?php

/**
 * This is the model base class for the table "priceclass".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Priceclass".
 *
 * Columns in table "priceclass" available as properties of the model,
 * followed by relations of table "priceclass" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property integer $amount
 * @property integer $type
 *
 * @property Channel[] $channels
 */
abstract class BasePriceclass extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'priceclass';
    }

    public static function representingColumn() {
        return 'name';
    }

    public function rules() {
        return array(
            array('name, amount, type', 'required'),
            array('amount, type', 'numerical', 'integerOnly'=>true),
            array('name', 'length', 'max'=>64),
            array('id, name, amount, type', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'channels' => array(self::HAS_MANY, 'Channel', 'price_class_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'name' => Yii::t('app', 'Nimi'),
                'amount' => Yii::t('app', 'Hinta'),
                'type' => Yii::t('app', 'Tyyppi'),
                'channels' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('name', $this->name, true);
        $criteria->compare('amount', $this->amount);
        $criteria->compare('type', $this->type);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}